# Coolify Configuration for YOLO Training System
# This file configures the deployment of the YOLO Training System on Coolify

version: '3.8'

services:
  yolo-training-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    environment:
      - HOST=0.0.0.0
      - PORT=8060
      - DEBUG=false
      - LOG_LEVEL=info
      - API_SECRET=${API_SECRET:-v63ilgo6j41o7xn75c}
      - CALLBACK_SECRET=${CALLBACK_SECRET:-changeme_callback_secret}
      - ALLOWED_ORIGINS=["${FRONTEND_URL:-http://localhost:3000}"]
      - DATA_DIR=/app/data
      - DATASETS_DIR=/app/data/datasets
      - MODELS_DIR=/app/data/models
      - CHECKPOINTS_DIR=/app/data/checkpoints
      - JOBS_DIR=/app/data/jobs
      - LOGS_DIR=/app/logs
      - DEFAULT_MODEL=yolov8n.pt
      - DEFAULT_EPOCHS=100
      - DEFAULT_BATCH_SIZE=16
      - DEFAULT_IMAGE_SIZE=640
      - MAX_CONCURRENT_JOBS=3
      - SYSTEM_MONITOR_INTERVAL=5
      - JOB_UPDATE_INTERVAL=2
    volumes:
      - yolo_data:/app/data
      - yolo_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - yolo_network

  # Optional: Frontend service (if deploying separately)
  yolo-frontend:
    build:
      context: ./interface-design
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=${BACKEND_URL:-http://localhost:8060}
      - VITE_API_TIMEOUT=10000
    depends_on:
      - yolo-training-system
    restart: unless-stopped
    networks:
      - yolo_network

volumes:
  yolo_data:
    driver: local
  yolo_logs:
    driver: local

networks:
  yolo_network:
    driver: bridge